# title: tinhkyaw@github
description: Personal collection of code snippets
# google_analytics:
# show_downloads: false
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions

github_username: tinhkyaw
baseurl: "/tinhkyaw"

exclude: www
