on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install and Run Zola
        run: |
          sudo snap install --edge zola
          npm install uglify-js
          cd www
          zola build --base-url ${{ secrets.DEPLOY_URL }} &&
          npm run abridge &&
          zola build --base-url ${{ secrets.DEPLOY_URL }}
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/pages-action@v1.3.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tinhkyaw
          directory: public
          workingDirectory: "www"
